### PR TITLE
Update com.google.ads.mediation:facebook to 6.11.0.0, FacebookAdapter…

### PR DESCRIPTION
**Pull request by javuxrc**
… error solution

### CODE REVIEW

**Review by sangram37 — APPROVED** [review]

**Comment by spivakov83** [comment]
Hi,
when will this PR be merged?

**Comment by rynrn** [comment]
+1

**Comment by ammarahm-ed** [comment]
I don't think the right thing to do here is pin down the library version. Instead it should be upgraded to latest.

**Comment by javuxrc** [comment]
Hello my friend! I set it to the version that worked, if left 6.+ I would install a version lower than 6.11 and it would fail. From 6.11 facebook is contemplated as meta. Hugs

**Comment by IB3N** [comment]
Would be great to get this merged so the package works and then work can be done on the refactor for the latest dependencies afterwards 🙏

**Comment by IB3N** [comment]
This fails on iOS as well. The fix is to specify `v6.11.0.0` in the `Podfile`

```
// MyApp/ios/Podfile
pod 'GoogleMobileAdsMediationFacebook', '6.11.0.0'
```

Perhaps this PR could include the iOS fix?

**Pull request closed without merging**
