### PR TITLE
Fix types! (and some other small things)

### PR DESCRIPTION
**Pull request by mrousavy**
This PR fixes the current types. They currently use hard-coded const types such as `AdManager.MAX_CONTENT_RATING.PG`. Instead, a more JS/TS friendly approach, would be to just use `'PG'`. Nothing more. 

image

So from this:

```ts
const config: Partial<config> = {
	maxAdContentRating: AdManager.MAX_AD_CONTENT_RATING.PG,
};
AdManager.setRequestConfiguration(config);
```

to this:

```ts
const config: Partial<AdManagerConfiguration> = {
	maxAdContentRating: 'PG',
};
AdManager.setRequestConfiguration(config);
```

(or directly like this:

```ts
AdManager.setRequestConfiguration({ maxAdContentRating: 'PG' });
```
)

Also, I fixed the `build.gradle` which was throwing me all kinds of compilation errors in my Android project, maybe because the versions are outdated, or I'm using Hermes, or both. Now it's the official build.gradle from the native modules template.

I somewhat cleaned up some indentations, and added null checks in the Java AdManager, also I used getBoolean instead of getInt for `true | false` values (!)

@ammarahm-ed I'd recommend a good cleanup of all the source files (Java, Objective-C, JavaScript, TypeScript) using some formatter tools like [ClangFormat](https://github.com/travisjeffery/ClangFormat-Xcode) for Objective-C, [google-java-format](https://github.com/google/google-java-format) for Java, and [ESLint](https://eslint.org) + [Prettier](https://prettier.io) for JavaScript/TypeScript. It makes code and diffs easier to read, and gives a solid uniform feeling for the entire codebase. Also maybe some null checks wouldn't hurt, especially in the `findViewById` stuff.

### CODE REVIEW

**Comment by mrousavy** [comment]
To add to my PR, I'd consider implementing the StarView yourself instead of using a dependency that was last updated 2 years ago. Here's an example `StarView` implementation I use in my app:


```tsx
import React, { useCallback } from 'react';
import { View, StyleSheet, StyleProp, ViewStyle } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import Colors from '../utils/Colors';

export interface StarViewProps {
  style?: StyleProp<ViewStyle>;
  stars: number;
  size?: number;
  fullIcon?: string;
  halfIcon?: string;
  emptyIcon?: string;
}

export default function StarView({
  style = undefined,
  stars,
  size = 15,
  fullIcon = 'shield',
  halfIcon = 'shield-half-full',
  emptyIcon = 'shield-outline',
}: StarViewProps): React.ReactElement | null {
  const renderIcons = useCallback(
    (_stars: number, _size: number, icons: React.ReactNode[] = [], emptyStars = 5): React.ReactNode[] => {
      if (_stars > 5) _stars = 5;
      if (_stars >= 1) {
        // 1 - 5
        icons.push(<Icon name={fullIcon} size={_size} key={`star-full${_stars}`} color={Colors.current.identity} />);
        return renderIcons(_stars - 1, _size, icons, emptyStars - 1);
      } else if (_stars >= 0.5) {
        // 0 - 1
        icons.push(<Icon name={halfIcon} size={_size} key={`star-half${_stars}`} color={Colors.current.identity} />);
        return renderIcons(_stars - 1, _size, icons, emptyStars - 1);
      }
      if (emptyStars > 0) {
        icons.push(<Icon name={emptyIcon} size={_size} key={`star-empty${emptyStars}`} color={Colors.current.identity} />);
        return renderIcons(_stars, _size, icons, emptyStars - 1);
      }
      // 0
      return icons;
    },
    [emptyIcon, fullIcon, halfIcon],
  );

  if (stars == null || typeof stars !== 'number') return null;

  const icons = renderIcons(stars, size);
  return <View style={[styles.row, style]}>{icons}</View>;
}

const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    marginTop: 1,
  },
});
```

**Comment by mrousavy** [comment]
Check out https://github.com/ammarahm-ed/react-native-admob-native-ads/pull/70 for the StarView issue.

**Comment by mrousavy** [comment]
For things like 

```tsx
<View
  style={[
    styles.container,
    props.style,
  ]}
>
```

I would also recommend memoizing those things. In a functional component it's very easy to use `useMemo`:

```ts
const style = useMemo(() => [styles.container, props.style], [props.style]);
// ...
<View style={style}>
```

As there are a lot of dynamic allocations (style arrays, custom style objects), this can impact performance a lot when we render Ads in Lists. Also I wouldn't use nested `?` and `:` operators... (personal preference on code readability of course)

**Comment by ammarahm-ed** [comment]
Thanks for these changes. I do not have much experience with Typescript, this looks more clean and easier to use. Also you are right, we can maybe add more null checks just incase the view is null in a special case.

You are right about the StarRatingView and thanks for adding it to the library. We also need to do something about the CallToActionView which uses the gesture-handler since other Touchables/Buttons do not detect the click function when it is assigned in the native code. That way we can remove almost all dependancies.

**Pull request merged**
