### PR TITLE
[iOS] Update to Google Ads SDK 8.x, Add trackingAuthorized boolean and Promise to requestConfiguration

### PR DESCRIPTION
**Pull request by wjaykim**
This changes make availability to set Facebook Audience Network SDK’s setAdvertiserTrackingEnabled flag which is needed for iOS14. 
Checkout: https://developers.facebook.com/docs/audience-network/setting-up/platform-setup/ios/advertising-tracking-enabled/

Additionally, I made change to index.d.ts, changing NativeAdView’s type from JSX.Element (functional component) to React.Component (class component) because functional component can’t have ref, so this has prevented to use loadAd() method in typescript.

### CODE REVIEW

**Comment by wjaykim** [comment]
Also I realized: All the flags must be set before startWithCompletionHandler is called, so I added it to the last of the setRequestConfiguration.

**Comment by wjaykim** [comment]
Also I made some changes related to #162

**Comment by wjaykim** [comment]
@ammarahm-ed please review these changes.

**Comment by wjaykim** [comment]
I updated iOS code compatible with Google Ad 8.x SDK.

**Comment by ammarahm-ed** [comment]
I will review these soon. Thanks for the work

**Comment by ammarahm-ed** [comment]
I think it should be `kGAMSimulatorID` on iOS instead of `kGADSimulatorID`

**Comment by wjaykim** [comment]
> I think it should be `kGAMSimulatorID` on iOS instead of `kGADSimulatorID` in AdManager

Oh, I didn't know the constant existed.
What's the difference between them?

**Comment by ammarahm-ed** [comment]
> > I think it should be `kGAMSimulatorID` on iOS instead of `kGADSimulatorID` in AdManager
> 
> Oh, I didn't know the constant existed.
> What's the difference between them?

We are using `GAMRequest` to request ads so its better to use the correct ID when setting test devices otherwise it might not work as expected.

**Comment by wjaykim** [comment]
> > > I think it should be `kGAMSimulatorID` on iOS instead of `kGADSimulatorID` in AdManager
> > 
> > Oh, I didn't know the constant existed.
> > What's the difference between them?
> 
> We are using `GAMRequest` to request ads so its better to use the correct ID when setting test devices otherwise it might not work as expected.

I see. I'll make change tomorrow.

**Comment by wjaykim** [comment]
@ammarahm-ed Changed.

**Comment by wjaykim** [comment]
I changed `onUnifiedNativeAdLoaded` to `onNativeAdLoaded`, but `onUnifiedNativeAdLoaded` also works on javascript with warning message for compatibility.

**Comment by ammarahm-ed** [comment]
@wjaykim the changes look fine. Maybe we should also change `RCTBubblingEventBlock` to `RCTDirectEventBlock` because that seems to be the correct way to send events.

**Comment by ammarahm-ed** [comment]
It would be great if you can update the docs with the relevant changes in AdManager and NativeAdView.

**Pull request merged**
